### PR TITLE
Magento 2.2x Compatibility

### PR DESCRIPTION
**Pull request by josh-carter**
- Composer Dependencies Updated by @adamj88 
- DI Compilation errors fixed by @josh-carter

To be released as interjar/bugsnag 2.2.0 or 3.3.0?

@adamj88 correct versioning to `3.3.0`?

### CODE REVIEW

**Comment by adamj88** [comment]
@josh-carter I've tested this on a CE 2.2 and it's compiling fine.

The version bump depends if it's backward compatible or not. Does it still di:compile with a 2.1.9 installation? If so it's only a just a patch, `2.2.1`, otherwise it's a breaking change and should be a major, `3.0.0`.

**Comment by Silarn** [comment]
No real code was changed, so this should be fully compatible with 2.1.*.

Magento 2.2 is much more picky about PHPDOC parameters when compiling and throws an error without this fix. That's the only problem - aside from the framework requirement update for composer.
